In [3]:
import numpy as numpy
arr=numpy.arange(10)
print (arr)
print (arr.dtype)
print (arr.shape)

[0 1 2 3 4 5 6 7 8 9]
int32
(10,)


In [1]:
import numpy as numpy
arr=numpy.arange(10)
arr_odd=arr[arr%2!=0]
arr_even=arr[arr%2==0]
print(arr_odd)
print(arr_even)

[1 3 5 7 9]
[0 2 4 6 8]


In [2]:
import numpy as numpy
arr=numpy.arange(10)
arr_update_1=numpy.where(arr%2==0, arr, 100)
print(arr_update_1)

[  0 100   2 100   4 100   6 100   8 100]
